schema: schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://graphql.contentful.com/content/v1/spaces/zg0hhjrvp0jj
      headers:
        user-agent: JS GraphQL
        Authorization: Bearer TH-0Mo-HO_AHYkFAIEAXi17uUsXpBXTegW0y7oO_xQE
      introspect: true
